# Generated by Django 3.1.14 on 2022-08-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(default=1, unique=True, verbose_name='ID пользователя Телеграм')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('username', models.CharField(max_length=255, verbose_name='Username Telegram')),
                ('sex', models.CharField(max_length=30, null=True, verbose_name='Пол искателя')),
                ('age', models.BigIntegerField(default=16, verbose_name='Возраст искателя')),
                ('city', models.CharField(max_length=255, null=True, verbose_name='Город искателя')),
                ('need_city', models.CharField(max_length=255, null=True, verbose_name='Город партнера')),
                ('longitude', models.FloatField(null=True, verbose_name='координаты пользователя')),
                ('latitude', models.FloatField(null=True, verbose_name='координаты пользователя')),
                ('verification', models.BooleanField(default=False, verbose_name='Верификация')),
                ('language', models.CharField(max_length=10, null=True, verbose_name='Язык пользователя')),
                ('varname', models.CharField(max_length=100, null=True, verbose_name='Публичное имя пользователя')),
                ('lifestyle', models.CharField(max_length=100, null=True, verbose_name='Стиль жизни пользователя')),
                ('is_banned', models.BooleanField(default=False, verbose_name='Забанен ли пользователь')),
                ('photo_id', models.CharField(max_length=400, null=True, verbose_name='Photo_ID')),
                ('commentary', models.CharField(max_length=300, null=True, verbose_name='Комментарий пользователя')),
                ('need_partner_sex', models.CharField(max_length=50, null=True, verbose_name='Пол партнера')),
                ('need_partner_age_min', models.IntegerField(default=16, verbose_name='Минимальный возраст партнера')),
                ('need_partner_age_max', models.IntegerField(default=24, verbose_name='Максимальный возраст партнера')),
                ('phone_number', models.BigIntegerField(null=True, verbose_name='Номер телефона')),
                ('status', models.BooleanField(default=False, verbose_name='Статус анкеты')),
                ('instagram', models.CharField(max_length=200, null=True, verbose_name='Ник в инстаграме')),
            ],
            options={
                'verbose_name': ('Пользователь Знакомств',),
                'verbose_name_plural': 'Пользователи Знакомств',
            },
        ),
        migrations.CreateModel(
            name='UserMeetings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(default=1, unique=True, verbose_name='ID пользователя Телеграм')),
                ('username', models.CharField(max_length=255, verbose_name='Username Telegram')),
                ('meetings_description', models.CharField(max_length=255, null=True, verbose_name='Описание встречи')),
            ],
            options={
                'verbose_name': ('Пользователь Мероприятий',),
                'verbose_name_plural': 'Пользователи Мероприятий',
            },
        ),
    ]
